### ISSUE TITLE
Exit screen gone 

### ISSUE THREAD

**Issue by zakir1988** [yuliskov/SmartYouTubeTV#164]
Where has the exit screen page gone I know we was able to double tap back button to exit the youtube tv app but I did prefer the exit screen as it was quick and look professional meaning was same as the official YouTube tv app

**Comment by dv8ed** [comment]
6.14.31 has pop-up screen to exit app but newer builds I can't exit out of app, I have to use my Android TV remote app on my mobile device to exit app. Please fix!

**Comment by zakir1988** [comment]
Exit dialog still not working needs an update still says double tap to exit the app

**Comment by yuliskov** [comment]
Should be fixed in 6.14.49

**Comment by yuliskov** [comment]
Definitely fixed in the latest update.

**Comment by zakir1988** [comment]
Hi the exit dialog still does not work as I can’t exit out of the app on the amazon Firestick I get the exit dialog screen when I press on exit it should exit out of the app it does not exit out of the app I have to double or few times tap the back button to exit the app can you  investigate what’s wrong and fix it still having problems thanks

**Comment by dv8ed** [comment]
For me Shield TV exit app is working again thank you! 6.14.53 popped up on my screen so I used that version never tried 6.14.49.

**Comment by WolfganP** [comment]
For me it's not that Exit isn't working, but the back function (ie right button of a mouse) not performing any action (so the Exit popup confirmation is not triggered)

**Comment by yuliskov** [comment]
@WolfganP I need keycode for this button. To obtain such code you could use app below.
https://drive.google.com/uc?id=0ByORA7yiJiQXdENBSENfczU4ZU0

**Comment by WolfganP** [comment]
Thx @yuliskov. The keycode for the mouse's right button (which acts as back in any other app) is KEYCODE_BACK (scancode=0,metastate=0,flags=0x0,ACTION_DOWN, deviceid=3, source=0x1002)

Besides, SmartYTTV doesn't respond to the Back button on the remote control of my remote either (both work in other apps).

**Comment by yuliskov** [comment]
@WolfganP are sure that mouse produces only one keycode? That's may be the source of problem. Usually there at least two: for up and down events. And show me the keycodes for your remote.

**Comment by WolfganP** [comment]
@yuliskov that's what the keytest app reported, but I'll run another test. and see if more events are collected. The remote's Back button pressing wasn't registered in the test, but I'll try again and report back.

**Comment by yuliskov** [comment]
@WolfganP ok, thanks

**Comment by zakir1988** [comment]
Thanks for fixing the exit screen dialog now works on the firestick can't wait to the the 4k version of the firestick when it comes out

**Comment by yuliskov** [comment]
@zakir1988 thank you for informing me

**Comment by WolfganP** [comment]
@yuliskov did a couple of extra test and yes, the mouse button click produces 2 events, but as the window is not scrolling the button release overwrites the press action.

Regarding the remote control, Back button is mapped to 4 / KEYCODE_BACK (scancode=158,metastate=0,flags=0x8,ACTION_DOWN, deviceid=6, source=0x301)

I hope it helps.

**Comment by yuliskov** [comment]
@WolfganP possible fix: https://github.com/yuliskov/SmartYouTubeTV/releases/download/6.14.57/SmartYouTubeTV_Orig_v6.14.57_r.apk

**Comment by yuliskov** [comment]
@WolfganP thanks for the your efforts. Seems that there is some unregistered events here. I'll update KeyTest app to catch more events.

**Comment by yuliskov** [comment]
@WolfganP updated version of the previous KeyTest app. Configured to catch more events.
https://drive.google.com/uc?id=1NGCi5E_0VPF4lhPE6Hz5jvj0VS-mqnQo

**Comment by WolfganP** [comment]
Thx @yuliskov . The previous version didn't scroll up events (just the latest one is displayed), what are you interested to see?

**Comment by yuliskov** [comment]
@WolfganP I'm interested to see last 4 events after you do press on the back key

**Comment by WolfganP** [comment]
Thx @yuliskov. Do you want the events be captured by this app in the foreground, or in SmartYT and KeyTest in the background?
Is there any way to export the events captured to a text file for easier sharing? Are the event registered in logcat somehow so I can post the full info?

**Comment by yuliskov** [comment]
@WolfganP I need info only from the KeyTest running in foreground.
Steps to get correct info is below:
1. Open KeyTest app.
2. Press the back key (or any key that you want to catch) on your input device.
3. Bring that info here.

**Comment by WolfganP** [comment]
I'm sorry @yuliskov but I can't install the updated KeyTest as it fails due to security warning that I couldn't dismiss (I've never had any issues like that). Maybe an app signature issue?
Original one that I posted info earlier worked like a charm thou.

**Comment by yuliskov** [comment]
@WolfganP I'll fix it soon. Thanks for the feedback.

**Comment by yuliskov** [comment]
@WolfganP below updated version of the KeyTest.
Now log is saved to the directory on your local storage.
Full log path is <storage>/Android/data/com.liskovsoft.mykeytest/cache/log.txt

https://drive.google.com/uc?id=1LVqx4MjO_-NOgEPK7E9pf9Et27TpOOZh

**Comment by yuliskov** [comment]
@WolfganP do you have any news?

**Comment by yuliskov** [comment]
Already fixed

**Comment by WolfganP** [comment]
@yuliskov sorry for the delay, I had no much time to test it thoroughly but my kids were using and updating SmartYTTV and found erratic behaviour (sometimes Back works, sometimes it doesn't).
I'll try to install latest version and keytest and report back.

**Comment by yuliskov** [comment]
@WolfganP ok, thanks.
